"""The build toolchain: which build plugin and which Gradle a Minecraft version needs.

Minecraft itself needs no Gradle. The build plugin does (fabric-loom 1.18.1 will
not load on a Gradle older than 9.7.0), and the loader team maintains the pair it
builds its own example mod with, one branch per Minecraft version. That pair is
the table this module reads:

    26.1   fabric-loom 1.15   Gradle 9.3.0
    26.2   fabric-loom 1.17   Gradle 9.5.1

An update moves the toolchain ONLY when the mod is below what the target needs.
Taking the newest plugin on every update used to break mods whose wrapper had not
followed, before a single test ran; and a plugin line moving for no Minecraft
reason is one more suspect when the matrix goes red.

The table is generated by scripts/refresh-toolchain.py and shipped with the code,
so nothing here touches the network. The plugin's own requirements (read from its
module metadata by the loader) are passed in as a callable.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .common import Failure
from .gradle import gradle_version_key, wrapper_gradle_version
from .versions import parse_version


@dataclass(frozen=True)
class Toolchain:
    #: a plugin LINE ("1.17") or an exact version ("0.12.12")
    buildtool: str
    gradle: str


@dataclass(frozen=True)
class Requirements:
    """What one build plugin version declares it needs. None: not declared."""

    gradle: str | None = None
    java: int | None = None


@dataclass(frozen=True)
class ToolchainPlan:
    buildtool: str | None
    buildtool_note: str
    #: the wrapper version to write, or the current one when nothing moves
    gradle: str | None
    gradle_note: str

    def gradle_moves(self, current: str | None) -> bool:
        return bool(self.gradle and current and self.gradle != current)


# --------------------------------------------------------------------------
# The table
# --------------------------------------------------------------------------
def load_table(path: Path) -> dict[str, Toolchain]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise Failure(f"cannot read the toolchain table {path}: {exc}") from exc
    return {
        minecraft: Toolchain(entry["buildtool"], entry["gradle"])
        for minecraft, entry in (document.get("versions") or {}).items()
    }


def dump_table(table: dict[str, Toolchain], source: str) -> str:
    ordered = sorted(table, key=lambda version: parse_version(version) or ())
    return (
        json.dumps(
            {
                "source": source,
                "versions": {
                    minecraft: {
                        "buildtool": table[minecraft].buildtool,
                        "gradle": table[minecraft].gradle,
                    }
                    for minecraft in ordered
                },
            },
            indent=2,
        )
        + "\n"
    )


_RELEASE_PREFIX = re.compile(r"(\d+\.\d+(?:\.\d+)?)-")


def required_for(
    table: dict[str, Toolchain], minecraft: str
) -> tuple[str, Toolchain] | None:
    """The table entry that governs `minecraft`, with the version it is listed under.

    An exact entry first. A release candidate or a snapshot is governed by the
    release it leads to (26.3-rc-3 -> 26.3). A version the table does not list
    yet takes the closest release BELOW it: a new Minecraft version builds with
    at least what the previous one needed, and the weekly refresh adds its own
    entry as soon as Fabric publishes it.
    """
    if minecraft in table:
        return minecraft, table[minecraft]

    numeric = parse_version(minecraft)
    if numeric is None:
        prefix = _RELEASE_PREFIX.match(minecraft)
        if prefix is None:
            # A weekly snapshot names no release: the newest known pair.
            if not table:
                return None
            newest = max(table, key=lambda version: parse_version(version) or ())
            return newest, table[newest]
        if prefix.group(1) in table:
            return prefix.group(1), table[prefix.group(1)]
        numeric = parse_version(prefix.group(1))

    below = [
        version
        for version in table
        if parse_version(version) is not None and parse_version(version) <= numeric
    ]
    if not below:
        return None
    closest = max(below, key=parse_version)
    return closest, table[closest]


# --------------------------------------------------------------------------
# Plugin lines
# --------------------------------------------------------------------------
def version_numbers(version: str) -> tuple[int, ...]:
    """(1, 17, 18) for "1.17.18", (1, 17) for "1.17-SNAPSHOT"."""
    numbers = []
    for chunk in re.split(r"[.-]", version):
        if not chunk.isdigit():
            break
        numbers.append(int(chunk))
    return tuple(numbers)


def satisfies(current: str, required: str) -> bool:
    """Is `current` at least the line (or exact version) `required`?

    Newer is fine: the toolchain is never moved DOWN, a mod ahead of Fabric's
    example knows why.
    """
    return version_numbers(current) >= version_numbers(required)


def in_line(version: str, required: str) -> bool:
    """A candidate for `required`: same major.minor, and not below it."""
    numbers, wanted = version_numbers(version), version_numbers(required)
    return numbers[:2] == wanted[:2] and numbers >= wanted


# --------------------------------------------------------------------------
# The decision
# --------------------------------------------------------------------------
def plan_toolchain(
    *,
    minecraft: str,
    table: dict[str, Toolchain],
    current_buildtool: str | None,
    current_gradle: str | None,
    java: int | None,
    candidates: Callable[[], list[str]],
    requirements: Callable[[str], Requirements | None],
    label: str,
    pinned: str | None = None,
) -> ToolchainPlan:
    """What the update writes for the build plugin and the Gradle wrapper.

    Nothing moves when the mod already meets the entry governing `minecraft`.
    Otherwise the plugin goes to the newest release of the required line whose
    declared Java the build has, and the wrapper to the highest of the table's
    Gradle and the one that plugin declares. `candidates` and `requirements` are
    only called when something has to move.
    """
    found = required_for(table, minecraft)
    # (version, why) candidates for the wrapper; the highest one wins.
    gradle_needs: list[tuple[str, str]] = []
    if found and found[1].gradle:
        gradle_needs.append((found[1].gradle, f"Minecraft {found[0]} needs Gradle {found[1].gradle}"))

    if pinned:
        buildtool, buildtool_note = pinned, "pinned"
        plugin = requirements(pinned)
        if plugin and plugin.java and java and plugin.java > java:
            raise Failure(
                f"{label} {pinned} requires Java >= {plugin.java}, java_version is {java}"
            )
    elif found is None:
        return ToolchainPlan(
            buildtool=current_buildtool,
            buildtool_note=f"unchanged, no toolchain known for Minecraft {minecraft}",
            gradle=current_gradle,
            gradle_note="unchanged" if current_gradle else "",
        )
    elif current_buildtool and satisfies(current_buildtool, found[1].buildtool):
        buildtool = current_buildtool
        buildtool_note = f"unchanged, Minecraft {found[0]} needs {found[1].buildtool}"
        plugin = None
    else:
        buildtool = _newest_in_line(found[1].buildtool, candidates(), requirements, java, label)
        buildtool_note = f"Minecraft {found[0]} needs {found[1].buildtool}"
        plugin = requirements(buildtool)

    if plugin and plugin.gradle:
        gradle_needs.append((plugin.gradle, f"{label} {buildtool} needs Gradle {plugin.gradle}"))

    if current_gradle is None:
        return ToolchainPlan(buildtool, buildtool_note, None, "no Gradle wrapper found, not checked")
    if not gradle_needs:
        return ToolchainPlan(buildtool, buildtool_note, current_gradle, "unchanged")
    need_gradle, why = max(gradle_needs, key=lambda need: gradle_version_key(need[0]))
    if gradle_version_key(current_gradle) >= gradle_version_key(need_gradle):
        return ToolchainPlan(buildtool, buildtool_note, current_gradle, "unchanged")
    return ToolchainPlan(
        buildtool, buildtool_note, need_gradle, f"{current_gradle} -> {need_gradle}, {why}"
    )


def _newest_in_line(
    line: str,
    candidates: list[str],
    requirements: Callable[[str], Requirements | None],
    java: int | None,
    label: str,
) -> str:
    """The newest release of `line` the build's Java can run.

    The Gradle a candidate needs is not a filter: the wrapper follows it. Java
    is, since java_version comes from Minecraft and nothing here may change it.
    """
    ordered = sorted(
        (version for version in set(candidates) if in_line(version, line)),
        key=version_numbers,
        reverse=True,
    )
    if not ordered:
        raise Failure(f"no stable {label} release in the {line} line")
    for version in ordered:
        plugin = requirements(version)
        if plugin is None or not plugin.java or not java or plugin.java <= java:
            return version
    raise Failure(
        f"every {label} {line}.x requires a newer Java than java_version {java}"
    )


# --------------------------------------------------------------------------
# Reading Fabric's example mod (used by scripts/refresh-toolchain.py)
# --------------------------------------------------------------------------
_LOOM_PROPERTY = re.compile(r"^loom_version\s*=\s*(\S+)\s*$", re.MULTILINE)
_LOOM_PLUGIN = re.compile(
    r"""id\s*\(?\s*["'](?:net\.fabricmc\.)?fabric-loom["']\s*\)?\s*version\s*\(?\s*["']([^"'$]+)["']"""
)


def buildtool_line(raw: str) -> str:
    """"1.17-SNAPSHOT" -> "1.17": a SNAPSHOT names a line, the update resolves a
    release of it. An exact version is kept as is."""
    return raw[: -len("-SNAPSHOT")] if raw.endswith("-SNAPSHOT") else raw


def loom_from_example(properties: str, build_script: str) -> str | None:
    """The Loom an example mod builds with: gradle.properties, else the plugin block."""
    match = _LOOM_PROPERTY.search(properties) or _LOOM_PLUGIN.search(build_script)
    return buildtool_line(match.group(1)) if match else None


def gradle_from_wrapper(text: str) -> str | None:
    return wrapper_gradle_version(text)
